-- ==============================================================================
-- AIoT Weather - Supabase Database Schema (PostgreSQL)
-- ==============================================================================
-- 專案說明：台灣 22 縣市即時與歷史天氣數據儲存資料表
-- 適用平臺：Supabase (https://supabase.com)
-- 
-- 使用方式：
-- 1. 登入 Supabase 控制台，建立或開啟您的專案
-- 2. 點選左側選單的「SQL Editor」
-- 3. 將本腳本內容全選貼上，並點擊「Run」執行
-- 4. 複製專案 Settings -> API 中的 Project URL 與 anon public key，
--    貼入 AIoT Weather 網頁右上角的「設定」視窗中即可！
-- ==============================================================================

-- 1. 建立 22 縣市歷史天氣快照記錄資料表
CREATE TABLE IF NOT EXISTS public.weather_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    county_id TEXT NOT NULL,                  -- 縣市代碼，例如 'TWTPE', 'TWTAO', 'TWKHH'
    county_name TEXT NOT NULL,                -- 縣市名稱，例如 '臺北市', '桃園市', '高雄市'
    temperature NUMERIC(4, 1),                -- 即時氣溫 (°C)
    humidity NUMERIC(4, 1),                   -- 相對濕度 (%)
    rainfall NUMERIC(5, 1) DEFAULT 0.0,       -- 累積降雨量 (mm)
    pm25 NUMERIC(4, 1) DEFAULT 0.0,           -- 細懸浮微粒 (μg/m³)
    pop NUMERIC(4, 1) DEFAULT 0.0,            -- 降雨機率 (%)
    weather_desc TEXT,                        -- 天氣現象文字，例如 '多雲時晴', '陰短暫雨'
    recorded_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 建立索引以確保按縣市及時間查詢歷史趨勢極速響應
CREATE INDEX IF NOT EXISTS idx_weather_history_county_time 
ON public.weather_history (county_id, recorded_at DESC);

CREATE INDEX IF NOT EXISTS idx_weather_history_time 
ON public.weather_history (recorded_at DESC);

-- 3. 啟用行級安全策略 (Row Level Security, RLS)
ALTER TABLE public.weather_history ENABLE ROW LEVEL SECURITY;

-- 允許前端匿名用戶讀取歷史天氣資料 (Public Read)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'weather_history' AND policyname = 'Public Read Weather History'
    ) THEN
        CREATE POLICY "Public Read Weather History"
        ON public.weather_history
        FOR SELECT
        TO anon, authenticated
        USING (true);
    END IF;
END $$;

-- 允許前端匿名用戶寫入即時天氣快照 (Public Insert)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'weather_history' AND policyname = 'Public Insert Weather History'
    ) THEN
        CREATE POLICY "Public Insert Weather History"
        ON public.weather_history
        FOR INSERT
        TO anon, authenticated
        WITH CHECK (true);
    END IF;
END $$;

-- 4. 插入示範初始資料 (24 小時歷史模擬測試資料)
-- 讓您在剛建立資料表後，就能立即在地圖儀表板看到流暢的趨勢曲線！
INSERT INTO public.weather_history (county_id, county_name, temperature, humidity, rainfall, pm25, pop, weather_desc, recorded_at)
VALUES
  ('TWTPE', '臺北市', 26.5, 78.0, 0.0, 18.0, 20.0, '多雲', NOW() - INTERVAL '24 hours'),
  ('TWTPE', '臺北市', 25.8, 82.0, 0.0, 15.0, 20.0, '晴時多雲', NOW() - INTERVAL '20 hours'),
  ('TWTPE', '臺北市', 25.2, 85.0, 0.0, 14.0, 15.0, '晴天', NOW() - INTERVAL '16 hours'),
  ('TWTPE', '臺北市', 27.0, 75.0, 0.0, 16.0, 10.0, '晴時多雲', NOW() - INTERVAL '12 hours'),
  ('TWTPE', '臺北市', 30.2, 65.0, 0.0, 20.0, 10.0, '晴天炎熱', NOW() - INTERVAL '8 hours'),
  ('TWTPE', '臺北市', 31.5, 62.0, 0.5, 22.0, 25.0, '多雲午後陣雨', NOW() - INTERVAL '4 hours'),
  ('TWTPE', '臺北市', 29.5, 68.0, 0.0, 18.0, 20.0, '晴時多雲', NOW() - INTERVAL '1 hour'),

  ('TWKHH', '高雄市', 28.0, 72.0, 0.0, 42.0, 10.0, '晴朗', NOW() - INTERVAL '24 hours'),
  ('TWKHH', '高雄市', 27.5, 75.0, 0.0, 38.0, 10.0, '晴朗', NOW() - INTERVAL '18 hours'),
  ('TWKHH', '高雄市', 29.8, 68.0, 0.0, 45.0, 10.0, '晴天', NOW() - INTERVAL '12 hours'),
  ('TWKHH', '高雄市', 32.5, 61.0, 0.0, 50.0, 10.0, '晴朗炎熱', NOW() - INTERVAL '6 hours'),
  ('TWKHH', '高雄市', 31.5, 64.0, 0.0, 46.0, 10.0, '晴天', NOW() - INTERVAL '1 hour'),

  ('TWTXG', '臺中市', 27.0, 70.0, 0.0, 30.0, 10.0, '晴天', NOW() - INTERVAL '24 hours'),
  ('TWTXG', '臺中市', 26.2, 74.0, 0.0, 28.0, 10.0, '晴天', NOW() - INTERVAL '18 hours'),
  ('TWTXG', '臺中市', 29.5, 66.0, 0.0, 33.0, 10.0, '晴朗', NOW() - INTERVAL '12 hours'),
  ('TWTXG', '臺中市', 31.2, 60.0, 0.0, 35.0, 10.0, '晴朗', NOW() - INTERVAL '6 hours'),
  ('TWTXG', '臺中市', 30.6, 65.0, 0.0, 32.0, 10.0, '晴朗無雲', NOW() - INTERVAL '1 hour');

-- 完成提示
COMMENT ON TABLE public.weather_history IS 'AIoT Weather 台灣 22 縣市即時與歷史氣象觀測快照記錄';
